server:
  port: 9090

spring:
  application:
    name: microservice-client

  data:
    mongodb:
      uri: mongodb://localhost:27017/futbolspace
      database: futbolspace
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka